spring:
  application:
    name: springcloud-eureka
server:
  port: 6001
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://peer2:6001/eureka/
