spring:
  application:
    name: springcloud-eureka
server:
  port: 6001
eureka:
  instance:
    hostname: peer1
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://peer1:6001/eureka/,http://peer2:6001/eureka/,http://peer3:6001/eureka/
