spring:
  application:
    name: springcloud-consumer-feign
server:
  port: 8083
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://peer1:6001/eureka/,http://peer2:6001/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
