server:
  port: 7001
spring:
  application:
    name: springcloud-provider

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://peer3:6001/eureka/,http://peer3:6001/eureka/
