zuul:
  routes:
    ribbon-api:
      path: /ribbon/**
      service-id: springcloud-ribbon
    api-a:
      path: /api-a/**
      service-id: springcloud-consumer-feign
    user:
      path: /user/**
      service-id: user-service
    order:
      path: /order/**
      service-id: order-service